<?php

if ( ! defined( 'ABSPATH' ) ) {
	// Exit if accessed directly.
	exit;
}

define( 'QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_VERSION', '1.0.7' );
define( 'QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_ABS_PATH', __DIR__ );
define( 'QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_REL_PATH', dirname( plugin_basename( __FILE__ ) ) );
define( 'QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_URL_PATH', plugin_dir_url( __FILE__ ) );
define( 'QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_ASSETS_PATH', QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_ABS_PATH . '/assets' );
define( 'QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_ASSETS_URL_PATH', QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_URL_PATH . 'assets' );
define( 'QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_INC_PATH', QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_ABS_PATH . '/inc' );
define( 'QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_INC_URL_PATH', QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_URL_PATH . 'inc' );
define( 'QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_ADMIN_PATH', QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_INC_PATH . '/admin' );
define( 'QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_ADMIN_URL_PATH', QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_INC_URL_PATH . '/admin' );
define( 'QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_ADMIN_ASSETS_PATH', QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_ADMIN_PATH . '/core-pages/assets' );
define( 'QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_ADMIN_ASSETS_URL_PATH', QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_ADMIN_URL_PATH . '/core-pages/assets' );

define( 'QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_GENERAL_MENU_NAME', 'qode_woocommerce_general_menu' );
define( 'QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_MENU_NAME', 'qode_variation_swatches_for_woocommerce_menu' );
define( 'QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_OPTIONS_NAME', 'qode_variation_swatches_for_woocommerce_options' );
define( 'QODE_VARIATION_SWATCHES_FOR_WOOCOMMERCE_MARKET_URL', 'https://qodeinteractive.com/products/plugins/qode-variation-swatches-for-woocommerce/' );
