<?php

define( 'ESKIL_MEMBERSHIP_VERSION', '1.0' );
define( 'ESKIL_MEMBERSHIP_ABS_PATH', dirname( __FILE__ ) );
define( 'ESKIL_MEMBERSHIP_REL_PATH', dirname( plugin_basename( __FILE__ ) ) );
define( 'ESKIL_MEMBERSHIP_URL_PATH', plugin_dir_url( __FILE__ ) );
define( 'ESKIL_MEMBERSHIP_ASSETS_PATH', ESKIL_MEMBERSHIP_ABS_PATH . '/assets' );
define( 'ESKIL_MEMBERSHIP_ASSETS_URL_PATH', ESKIL_MEMBERSHIP_URL_PATH . 'assets' );
define( 'ESKIL_MEMBERSHIP_INC_PATH', ESKIL_MEMBERSHIP_ABS_PATH . '/inc' );
define( 'ESKIL_MEMBERSHIP_INC_URL_PATH', ESKIL_MEMBERSHIP_URL_PATH . 'inc' );
define( 'ESKIL_MEMBERSHIP_LOGIN_MODAL_PATH', ESKIL_MEMBERSHIP_INC_PATH . '/login-modal' );
define( 'ESKIL_MEMBERSHIP_LOGIN_MODAL_URL_PATH', ESKIL_MEMBERSHIP_INC_URL_PATH . 'login-modal' );
